services:
  nugs-downloader:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: nugs-downloader:latest
    container_name: nugs-downloader
    ports:
      - "8090:8090"
    environment:
      NUGS_CONFIG_PATH: /app/data/private_sources/nugs/config.json
      NUGS_CREDENTIALS_PATH: /app/data/private_sources/nugs/secrets/nugs_credentials.enc
      NUGS_CREDENTIALS_KEY_PATH: /app/data/private_sources/nugs/secrets/nugs_credentials.key
    volumes:
      - "../download_history.sqlite3:/app/download_history.sqlite3"
      - "../data/private_sources/nugs:/app/data/private_sources/nugs"
    restart: unless-stopped
